mode = "dark"
background = "#250f07"
dark_background = "#1b0803"
darker_background = "#140502"
lighter_background = "#34170d"
selection = "#4f2611"
muted = "#633c2e"
dark_foreground = "#a27363"
foreground = "#e6d4c3"
bright_foreground = "#faecde"
accent = "#f47f46"
red = "#e9897e"
bright_red = "#fe9c91"
orange = "#f2a26a"
yellow = "#e0c262"
bright_yellow = "#f6d56b"
green = "#88cf8a"
bright_green = "#96e498"
cyan = "#40d2d2"
bright_cyan = "#45e8e8"
blue = "#60b3dc"
bright_blue = "#8bbeff"
magenta = "#d190d4"
bright_magenta = "#e8a0ec"
accent_color = "orange"
icon_style = "tinted"
icon_tint = "accent"
