mode = "dark"
background = "#22256b"
dark_background = "#1b1d5b"
darker_background = "#17194e"
lighter_background = "#2a2d84"
selection = "#1d49a0"
muted = "#4b55a0"
dark_foreground = "#7d8ed0"
foreground = "#c8d6ff"
bright_foreground = "#e9eefe"
accent = "#9bbeff"
red = "#fea69c"
bright_red = "#fec4bc"
orange = "#ffc29a"
yellow = "#f8dc86"
bright_yellow = "#fff1c9"
green = "#a6e8a7"
bright_green = "#b5feb6"
cyan = "#70ebeb"
bright_cyan = "#88fffe"
blue = "#97c4fe"
bright_blue = "#b8d7fe"
magenta = "#e9abec"
bright_magenta = "#fcbfff"
accent_color = "blue"
icon_style = "dark"
