mode = "light"
background = "#f3f9f1"
dark_background = "#e8efe5"
darker_background = "#dee6da"
lighter_background = "#e3ebdf"
selection = "#baddc0"
muted = "#b0b9ab"
dark_foreground = "#6b7566"
foreground = "#282f35"
bright_foreground = "#151b21"
accent = "#21763c"
red = "#b24840"
bright_red = "#c7534a"
orange = "#ac5701"
yellow = "#8d7102"
bright_yellow = "#9e8003"
green = "#267d30"
bright_green = "#2f8d39"
cyan = "#057575"
bright_cyan = "#098585"
blue = "#2769b7"
bright_blue = "#3077cd"
magenta = "#99519e"
bright_magenta = "#ac5db1"
accent_color = "auto"
