mode = "dark"
background = "#0d0b08"
dark_background = "#060504"
darker_background = "#030202"
lighter_background = "#18140f"
selection = "#362201"
muted = "#403931"
dark_foreground = "#887f73"
foreground = "#e2d5c4"
bright_foreground = "#f7eddf"
accent = "#e4b473"
red = "#db978c"
orange = "#e3ae89"
yellow = "#d9c68b"
green = "#a7ca93"
cyan = "#7bd0c3"
blue = "#93aae1"
magenta = "#d199c2"
bright_red = "#f5a79b"
bright_yellow = "#f0da95"
bright_green = "#b7dfa0"
bright_cyan = "#85e6d7"
bright_blue = "#a2bcfc"
bright_magenta = "#e9aad7"
accent_color = "auto"
icon_style = "dark"
