mode = "dark"
background = "#051427"
dark_background = "#020c1d"
darker_background = "#010715"
lighter_background = "#0a1e38"
selection = "#442a01"
muted = "#2c4668"
dark_foreground = "#6482aa"
foreground = "#e2d6c2"
bright_foreground = "#f7eddd"
accent = "#f8b14e"
red = "#ed8c81"
bright_red = "#ffa196"
orange = "#f6a56d"
yellow = "#e3c566"
bright_yellow = "#fad86f"
green = "#8bd28d"
bright_green = "#99e89b"
cyan = "#44d6d6"
bright_cyan = "#4aebeb"
blue = "#75aef5"
bright_blue = "#91c1ff"
magenta = "#d493d8"
bright_magenta = "#eba3ef"
accent_color = "auto"
icon_style = "dark"
