mode = "dark"
background = "#10161d"
dark_background = "#090e14"
darker_background = "#05090e"
lighter_background = "#18202a"
selection = "#1b3350"
muted = "#3c4857"
dark_foreground = "#738295"
foreground = "#d1d8e1"
bright_foreground = "#e9eff6"
accent = "#91c1fd"
red = "#db959a"
orange = "#eaa98f"
yellow = "#d0cb89"
green = "#8fcfa8"
cyan = "#77ced9"
blue = "#85afdc"
magenta = "#c19ed5"
bright_red = "#f5a5aa"
bright_yellow = "#e5de94"
bright_green = "#9ce4b8"
bright_cyan = "#80e3f0"
bright_blue = "#92c2f6"
bright_magenta = "#d7afed"
accent_color = "auto"
icon_style = "dark"
