mode = "light"
background = "#f9f6df"
dark_background = "#f0ecd1"
darker_background = "#e7e2c4"
lighter_background = "#ece7c9"
selection = "#b9dcb9"
muted = "#bab596"
dark_foreground = "#777354"
foreground = "#233226"
bright_foreground = "#101f13"
accent = "#2d8336"
red = "#b24840"
bright_red = "#c7534a"
orange = "#ac5701"
yellow = "#8d7102"
bright_yellow = "#9e8003"
green = "#267d30"
bright_green = "#2f8d39"
cyan = "#057575"
bright_cyan = "#098585"
blue = "#2769b7"
bright_blue = "#3077cd"
magenta = "#99519e"
bright_magenta = "#ac5db1"
accent_color = "green"
