mode = "dark"
background = "#07090c"
dark_background = "#030406"
darker_background = "#010203"
lighter_background = "#0e1318"
selection = "#002a2b"
muted = "#313941"
dark_foreground = "#76828d"
foreground = "#89f58f"
bright_foreground = "#caffcb"
accent = "#3be1e1"
red = "#ff847d"
bright_red = "#fea69e"
orange = "#ffa666"
yellow = "#f2c50e"
bright_yellow = "#ffdb69"
green = "#72dd78"
bright_green = "#80f386"
cyan = "#03dcdc"
bright_cyan = "#06f2f2"
blue = "#7aaffe"
bright_blue = "#9ac3ff"
magenta = "#fe7fc0"
bright_magenta = "#ffa3cf"
accent_color = "green"
icon_style = "tinted"
icon_tint = "accent"
