mode = "light"
background = "#e8f4fa"
dark_background = "#dbebf3"
darker_background = "#d0e1ea"
lighter_background = "#d5e6ef"
selection = "#a5d8e3"
muted = "#a1b5bf"
dark_foreground = "#607580"
foreground = "#222f3c"
bright_foreground = "#101c28"
accent = "#06899d"
red = "#b9463f"
bright_red = "#ce5249"
orange = "#b05a02"
yellow = "#907402"
bright_yellow = "#a18304"
green = "#1f812d"
bright_green = "#299236"
cyan = "#047879"
bright_cyan = "#078989"
blue = "#226bc0"
bright_blue = "#2b7ad6"
magenta = "#9f51a4"
bright_magenta = "#b25cb7"
accent_color = "auto"
