mode = "dark"
background = "#070a18"
dark_background = "#03040f"
darker_background = "#010208"
lighter_background = "#0e1426"
selection = "#381a32"
muted = "#313953"
dark_foreground = "#747f9f"
foreground = "#d0d7ec"
bright_foreground = "#e9eefe"
accent = "#ed6cd5"
red = "#ff796d"
bright_red = "#fe9c91"
orange = "#ff9b52"
yellow = "#ebbf0d"
bright_yellow = "#ffd337"
green = "#6bd672"
bright_green = "#79ec80"
cyan = "#09d5d5"
bright_cyan = "#0deaeb"
blue = "#67aaff"
bright_blue = "#8bbeff"
magenta = "#df81e5"
bright_magenta = "#f791fd"
accent_color = "auto"
icon_style = "dark"
