mode = "dark"
background = "#060606"
dark_background = "#020202"
darker_background = "#010101"
lighter_background = "#100e0e"
selection = "#37120f"
muted = "#373133"
dark_foreground = "#877d80"
foreground = "#d7d7d7"
bright_foreground = "#eeeeee"
accent = "#e94740"
red = "#f14e46"
bright_red = "#fab3aa"
orange = "#ebb896"
yellow = "#e2d099"
bright_yellow = "#f9e4a3"
green = "#b0d3a4"
bright_green = "#c0e9b2"
cyan = "#8cd5e2"
bright_cyan = "#95ebfa"
blue = "#94b7e4"
bright_blue = "#a2cafe"
magenta = "#d0a7d2"
bright_magenta = "#e7b8e9"
accent_color = "graphite"
icon_style = "dark"
