mode = "dark"
background = "#170d05"
dark_background = "#0f0602"
darker_background = "#090301"
lighter_background = "#241609"
selection = "#3f2503"
muted = "#4f3b29"
dark_foreground = "#947b65"
foreground = "#fece92"
bright_foreground = "#ffebd3"
accent = "#ffa839"
red = "#e98a7a"
bright_red = "#fe9c8c"
orange = "#f2a26a"
yellow = "#e0c262"
bright_yellow = "#f6d56b"
green = "#a9c870"
bright_green = "#badd7b"
cyan = "#48d3c5"
bright_cyan = "#4ee9d9"
blue = "#50b3e8"
bright_blue = "#60c7fe"
magenta = "#e08bbc"
bright_magenta = "#f99bd1"
accent_color = "orange"
icon_style = "tinted"
icon_tint = "accent"
