mode = "dark"
background = "#10091a"
dark_background = "#080411"
darker_background = "#04020a"
lighter_background = "#1a1228"
selection = "#3c1b35"
muted = "#413755"
dark_foreground = "#85799e"
foreground = "#dad3e9"
bright_foreground = "#f1ebfd"
accent = "#f252d8"
red = "#ff796d"
bright_red = "#fe9c91"
orange = "#ff9b52"
yellow = "#ebbf0d"
bright_yellow = "#ffd337"
green = "#65d86d"
bright_green = "#72ed7b"
cyan = "#09d5d5"
bright_cyan = "#0deaeb"
blue = "#67aaff"
bright_blue = "#8bbeff"
magenta = "#e27ee8"
bright_magenta = "#f88fff"
accent_color = "pink"
icon_style = "tinted"
icon_tint = "accent"
