mode = "dark"
background = "#141712"
dark_background = "#0d0f0b"
darker_background = "#080a07"
lighter_background = "#1e221a"
selection = "#2c3813"
muted = "#444a3e"
dark_foreground = "#7b8374"
foreground = "#d6d9ce"
bright_foreground = "#edf0e7"
accent = "#baed3f"
red = "#e88f85"
bright_red = "#ffa196"
orange = "#f1a774"
yellow = "#e1c570"
bright_yellow = "#f7d979"
green = "#90d192"
bright_green = "#9ee6a0"
cyan = "#57d4d4"
bright_cyan = "#5de9e9"
blue = "#7aaeef"
bright_blue = "#91c1ff"
magenta = "#d195d4"
bright_magenta = "#e8a6ec"
accent_color = "green"
icon_style = "tinted"
icon_tint = "accent"
