mode = "dark"
background = "#08090d"
dark_background = "#030406"
darker_background = "#010203"
lighter_background = "#10121a"
selection = "#291c3c"
muted = "#343843"
dark_foreground = "#7a8090"
foreground = "#d5d7de"
bright_foreground = "#eceef4"
accent = "#c9acff"
red = "#ff8579"
bright_red = "#fea69c"
orange = "#ffa666"
yellow = "#f2c50e"
bright_yellow = "#ffdb69"
green = "#72dd78"
bright_green = "#80f386"
cyan = "#03dcdc"
bright_cyan = "#06f2f2"
blue = "#73b1ff"
bright_blue = "#97c4fe"
magenta = "#e688ec"
bright_magenta = "#f99cff"
accent_color = "multicolor"
icon_style = "dark"
