mode = "light"
background = "#f4f7e8"
dark_background = "#eaeddb"
darker_background = "#e0e4cf"
lighter_background = "#e5e9d4"
selection = "#c2dab6"
muted = "#b3b7a0"
dark_foreground = "#71745d"
foreground = "#23331f"
bright_foreground = "#101f0d"
accent = "#5a8a3d"
red = "#a94f47"
bright_red = "#be5b52"
orange = "#a65c20"
yellow = "#8d7102"
bright_yellow = "#9e8003"
green = "#357a3a"
bright_green = "#3e8b44"
cyan = "#057575"
bright_cyan = "#098585"
blue = "#346aac"
bright_blue = "#3d78c2"
magenta = "#945798"
bright_magenta = "#a763ab"
accent_color = "green"
