mode = "light"
background = "#f8f5ee"
dark_background = "#efebe1"
darker_background = "#e5e1d6"
lighter_background = "#eae6da"
selection = "#f0c3d3"
muted = "#b9b4a6"
dark_foreground = "#777161"
foreground = "#1f2d4c"
bright_foreground = "#0d1936"
accent = "#e2348d"
red = "#bd423a"
bright_red = "#d24d45"
orange = "#b05a02"
yellow = "#907402"
bright_yellow = "#a18304"
green = "#118226"
bright_green = "#1d9330"
cyan = "#047879"
bright_cyan = "#078989"
blue = "#186bc5"
bright_blue = "#2279dc"
magenta = "#a14da7"
bright_magenta = "#b459ba"
accent_color = "pink"
