mode = "light"
background = "#f9f5e6"
dark_background = "#f0ebd9"
darker_background = "#e7e2cd"
lighter_background = "#ece6d2"
selection = "#efc3d5"
muted = "#bab49e"
dark_foreground = "#78725b"
foreground = "#2d2d33"
bright_foreground = "#1a1a1f"
accent = "#d94393"
red = "#c0453d"
bright_red = "#d65048"
orange = "#b45c03"
yellow = "#937702"
bright_yellow = "#a58604"
green = "#178529"
bright_green = "#229633"
cyan = "#027c7c"
bright_cyan = "#068c8c"
blue = "#1d6ec9"
bright_blue = "#267cdf"
magenta = "#a550aa"
bright_magenta = "#b75cbd"
accent_color = "pink"
