mode = "dark"
background = "#1d1106"
dark_background = "#140902"
darker_background = "#0e0501"
lighter_background = "#2b1a0a"
selection = "#412c05"
muted = "#573f2a"
dark_foreground = "#977a61"
foreground = "#e5d6ba"
bright_foreground = "#f9edd7"
accent = "#f5b33b"
red = "#ed8c81"
bright_red = "#ffa196"
orange = "#f6a56d"
yellow = "#e3c566"
bright_yellow = "#fad86f"
green = "#8bd28d"
bright_green = "#99e89b"
cyan = "#44d6d6"
bright_cyan = "#4aebeb"
blue = "#75aef5"
bright_blue = "#91c1ff"
magenta = "#d493d8"
bright_magenta = "#eba3ef"
accent_color = "yellow"
icon_style = "tinted"
icon_tint = "accent"
