mode = "dark"
background = "#06162c"
dark_background = "#020e21"
darker_background = "#010919"
lighter_background = "#0a203d"
selection = "#01394a"
muted = "#2c496e"
dark_foreground = "#6282ae"
foreground = "#ccdae4"
bright_foreground = "#e5f0f8"
accent = "#7ad5f8"
red = "#e89e95"
bright_red = "#ffb0a6"
orange = "#f2b58c"
yellow = "#e6d08c"
bright_yellow = "#fce396"
green = "#a3d7a3"
bright_green = "#b1edb2"
cyan = "#7bdad9"
bright_cyan = "#84f0ef"
blue = "#8db7ed"
bright_blue = "#a2caff"
magenta = "#d5a4d7"
bright_magenta = "#ecb4ef"
accent_color = "auto"
icon_style = "dark"
