mode = "light"
background = "#fefdda"
dark_background = "#d8f9fb"
darker_background = "#ebe9bd"
lighter_background = "#f5f3cc"
selection = "#c0d7ff"
muted = "#bebc8e"
dark_foreground = "#77744a"
foreground = "#2a2e33"
bright_foreground = "#171b1f"
accent = "#3860ac"
red = "#b24840"
bright_red = "#c7534a"
orange = "#ac5701"
yellow = "#8d7102"
bright_yellow = "#9e8003"
green = "#267d30"
bright_green = "#2f8d39"
cyan = "#057575"
bright_cyan = "#098585"
blue = "#2769b7"
bright_blue = "#3077cd"
magenta = "#99519e"
bright_magenta = "#ac5db1"
accent_color = "auto"
