mode = "dark"
background = "#161332"
dark_background = "#0f0b27"
darker_background = "#0a071e"
lighter_background = "#201c44"
selection = "#023e3c"
muted = "#464377"
dark_foreground = "#7b78b4"
foreground = "#d5d5eb"
bright_foreground = "#ecedff"
accent = "#43d3cc"
red = "#f2897e"
bright_red = "#ffa196"
orange = "#faa365"
yellow = "#e6c45a"
bright_yellow = "#fcd863"
green = "#86d489"
bright_green = "#94e997"
cyan = "#2ad7d7"
bright_cyan = "#2eeded"
blue = "#70adfb"
bright_blue = "#91c1ff"
magenta = "#d790db"
bright_magenta = "#eea0f3"
accent_color = "auto"
icon_style = "dark"
