mode = "dark"
background = "#031222"
dark_background = "#010b18"
darker_background = "#000611"
lighter_background = "#071d32"
selection = "#05381e"
muted = "#284561"
dark_foreground = "#6383a5"
foreground = "#cbdae2"
bright_foreground = "#e4f1f7"
accent = "#5aea98"
red = "#f6857a"
bright_red = "#ffa196"
orange = "#ffa15c"
yellow = "#e8c44e"
bright_yellow = "#fed756"
green = "#81d584"
bright_green = "#8eeb92"
cyan = "#06d8d9"
bright_cyan = "#0aeeee"
blue = "#6dadff"
bright_blue = "#91c1ff"
magenta = "#c688f2"
bright_magenta = "#f19df6"
accent_color = "auto"
icon_style = "dark"
