mode = "dark"
background = "#0b376a"
dark_background = "#072f5b"
darker_background = "#07294f"
lighter_background = "#094381"
selection = "#045e8c"
muted = "#39659b"
dark_foreground = "#80aace"
foreground = "#ccdae4"
bright_foreground = "#e5f0f8"
accent = "#b0eaf4"
red = "#ffb5ac"
bright_red = "#ffd2cc"
orange = "#fed0b2"
yellow = "#ffe79d"
bright_yellow = "#fff5d7"
green = "#b5f0b5"
bright_green = "#d6ffd6"
cyan = "#87f3f2"
bright_cyan = "#c5fffe"
blue = "#a8ceff"
bright_blue = "#c9e0fe"
magenta = "#f0b7f2"
bright_magenta = "#fdd0fe"
accent_color = "blue"
icon_style = "dark"
