mode = "dark"
background = "#06132a"
dark_background = "#030b1f"
darker_background = "#010717"
lighter_background = "#0b1d3b"
selection = "#412c00"
muted = "#2d456c"
dark_foreground = "#6581af"
foreground = "#ccd9e8"
bright_foreground = "#e5f0fc"
accent = "#f3b94c"
red = "#ed8c81"
bright_red = "#ffa196"
orange = "#f6a56d"
yellow = "#e3c566"
bright_yellow = "#fad86f"
green = "#8bd28d"
bright_green = "#99e89b"
cyan = "#44d6d6"
bright_cyan = "#4aebeb"
blue = "#75aef5"
bright_blue = "#91c1ff"
magenta = "#d493d8"
bright_magenta = "#eba3ef"
accent_color = "auto"
icon_style = "dark"
