mode = "dark"
background = "#000f1b"
dark_background = "#000710"
darker_background = "#000409"
lighter_background = "#00192a"
selection = "#02302c"
muted = "#0f415f"
dark_foreground = "#5386aa"
foreground = "#badfe6"
bright_foreground = "#d7f5fa"
accent = "#14ecda"
red = "#fa887d"
bright_red = "#fea69c"
orange = "#ffa666"
yellow = "#ebc751"
bright_yellow = "#ffdb69"
green = "#84d987"
bright_green = "#92ee95"
cyan = "#03dcdc"
bright_cyan = "#06f2f2"
blue = "#73b1ff"
bright_blue = "#97c4fe"
magenta = "#d384e5"
bright_magenta = "#f5a1f9"
accent_color = "auto"
icon_style = "dark"
