mode = "dark"
background = "#1a1514"
dark_background = "#110d0d"
darker_background = "#0c0808"
lighter_background = "#261e1e"
selection = "#4d2525"
muted = "#514444"
dark_foreground = "#8d7b7b"
foreground = "#ddd5d5"
bright_foreground = "#f3eded"
accent = "#e63745"
red = "#f45058"
bright_red = "#f4a298"
orange = "#e5a880"
yellow = "#d9c37f"
bright_yellow = "#efd689"
green = "#96ca97"
bright_green = "#a5e0a5"
cyan = "#6ecdcc"
bright_cyan = "#76e2e2"
blue = "#81abe0"
bright_blue = "#8fbefa"
magenta = "#c897ca"
bright_magenta = "#dfa8e1"
accent_color = "red"
icon_style = "dark"
