mode = "dark"
background = "#17181a"
dark_background = "#0f1112"
darker_background = "#0a0b0c"
lighter_background = "#202327"
selection = "#42330a"
muted = "#454b51"
dark_foreground = "#79818a"
foreground = "#d9d7d2"
bright_foreground = "#f0eeea"
accent = "#e1cc99"
red = "#da9c94"
bright_red = "#f3aca3"
orange = "#e4b290"
yellow = "#dcca92"
bright_yellow = "#f2dd9d"
green = "#a3cea3"
bright_green = "#b2e4b2"
cyan = "#85d1d0"
bright_cyan = "#8ee6e5"
blue = "#8eb1dd"
bright_blue = "#9cc4f8"
magenta = "#caa1cc"
bright_magenta = "#e1b2e3"
accent_color = "graphite"
icon_style = "dark"
