mode = "light"
background = "#efeeeb"
dark_background = "#e6e4df"
darker_background = "#dddbd4"
lighter_background = "#e2dfd9"
selection = "#b0ceee"
muted = "#b1aea5"
dark_foreground = "#767165"
foreground = "#2c2e31"
bright_foreground = "#191b1d"
accent = "#3b5876"
red = "#9a5049"
bright_red = "#af5c53"
orange = "#985b2d"
yellow = "#846c1b"
bright_yellow = "#957b1e"
green = "#3b723e"
bright_green = "#448247"
cyan = "#076f6f"
bright_cyan = "#017f7f"
blue = "#39659b"
bright_blue = "#4273b0"
magenta = "#89568c"
bright_magenta = "#9b629e"
accent_color = "graphite"
