mode = "dark"
background = "#1e1a15"
dark_background = "#16120e"
darker_background = "#100d09"
lighter_background = "#2b241c"
selection = "#4b3210"
muted = "#564b3f"
dark_foreground = "#8b7e6f"
foreground = "#ded6c9"
bright_foreground = "#f4eee3"
accent = "#fcaf41"
red = "#e08f86"
bright_red = "#f99f94"
orange = "#e9a679"
yellow = "#dbc276"
bright_yellow = "#f1d680"
green = "#92cc93"
bright_green = "#a0e1a1"
cyan = "#63cfc9"
bright_cyan = "#6be5de"
blue = "#7cabe6"
bright_blue = "#8bbeff"
magenta = "#cb95ce"
bright_magenta = "#e2a5e5"
accent_color = "orange"
icon_style = "dark"
