mode = "light"
background = "#fafafa"
dark_background = "#f2eff0"
darker_background = "#e9e5e6"
lighter_background = "#eeeaeb"
selection = "#f8c9c2"
muted = "#beb7b9"
dark_foreground = "#7a6e71"
foreground = "#2e2e2e"
bright_foreground = "#1b1b1b"
accent = "#df2321"
red = "#b24840"
bright_red = "#c7534a"
orange = "#ac5701"
yellow = "#8d7102"
bright_yellow = "#9e8003"
green = "#267d30"
bright_green = "#2f8d39"
cyan = "#057575"
bright_cyan = "#098585"
blue = "#2769b7"
bright_blue = "#3077cd"
magenta = "#99519e"
bright_magenta = "#ac5db1"
accent_color = "red"
