mode = "light"
background = "#efebe2"
dark_background = "#e7e0d5"
darker_background = "#ded7ca"
lighter_background = "#e3dbcf"
selection = "#b0caeb"
muted = "#b2aa9b"
dark_foreground = "#7a7060"
foreground = "#38292f"
bright_foreground = "#24161c"
accent = "#4973ab"
red = "#a65249"
orange = "#966542"
yellow = "#85733a"
green = "#2d7a51"
cyan = "#07747f"
blue = "#496b96"
magenta = "#865f9b"
bright_red = "#bb5d53"
bright_yellow = "#96823f"
bright_green = "#338a5d"
bright_cyan = "#008491"
bright_blue = "#5279ac"
bright_magenta = "#976caf"
accent_color = "auto"
