mode = "dark"
background = "#190f0a"
dark_background = "#100805"
darker_background = "#0a0403"
lighter_background = "#261811"
selection = "#45240f"
muted = "#523d33"
dark_foreground = "#947a6e"
foreground = "#e4d5c7"
bright_foreground = "#f8ece1"
accent = "#e18752"
red = "#e1897f"
bright_red = "#fb988d"
orange = "#eba16e"
yellow = "#dabf69"
bright_yellow = "#f0d273"
green = "#91c985"
bright_green = "#a0de93"
cyan = "#55cec0"
bright_cyan = "#5ce4d5"
blue = "#74a7e8"
bright_blue = "#86bafe"
magenta = "#cb8fce"
bright_magenta = "#e29fe5"
accent_color = "orange"
icon_style = "tinted"
icon_tint = "accent"
