mode = "dark"
background = "#140504"
dark_background = "#0b0201"
darker_background = "#050000"
lighter_background = "#210b0a"
selection = "#3c1714"
muted = "#4e2e2c"
dark_foreground = "#9d7571"
foreground = "#fdcac0"
bright_foreground = "#fee9e5"
accent = "#ed4b43"
red = "#d2837a"
bright_red = "#eb9288"
orange = "#df9773"
yellow = "#dfad6d"
bright_yellow = "#f7bf77"
green = "#b2b467"
bright_green = "#c5c771"
cyan = "#61c3aa"
bright_cyan = "#6ad8bd"
blue = "#709ed8"
bright_blue = "#7eb1f3"
magenta = "#b98ac7"
bright_magenta = "#ce9bdf"
accent_color = "red"
icon_style = "tinted"
icon_tint = "accent"
