mode = "light"
background = "#ebf8fc"
dark_background = "#deeff4"
darker_background = "#d2e5eb"
lighter_background = "#d7eaf0"
selection = "#aed8ef"
muted = "#a3b9c0"
dark_foreground = "#5f767e"
foreground = "#1a3040"
bright_foreground = "#061d2b"
accent = "#017ca7"
red = "#a94f47"
bright_red = "#be5b52"
orange = "#a65c20"
yellow = "#8d7102"
bright_yellow = "#9e8003"
green = "#357a3a"
bright_green = "#3e8b44"
cyan = "#057575"
bright_cyan = "#098585"
blue = "#346aac"
bright_blue = "#3d78c2"
magenta = "#945798"
bright_magenta = "#a763ab"
accent_color = "blue"
