mode = "dark"
background = "#1e0e33"
dark_background = "#150727"
darker_background = "#0f041f"
lighter_background = "#2a1645"
selection = "#591a3c"
muted = "#533c78"
dark_foreground = "#8a71b5"
foreground = "#e1d1e4"
bright_foreground = "#f6eaf9"
accent = "#fe6ab9"
red = "#fe8b7f"
bright_red = "#feaba1"
orange = "#ffab70"
yellow = "#f1ca47"
bright_yellow = "#ffdf7c"
green = "#81dd85"
bright_green = "#8ff394"
cyan = "#14dfe0"
bright_cyan = "#02f6f6"
blue = "#7ab4fe"
bright_blue = "#9dc7fe"
magenta = "#e491e9"
bright_magenta = "#faa2ff"
accent_color = "pink"
icon_style = "tinted"
icon_tint = "accent"
