mode = "light"
background = "#e9ebee"
dark_background = "#dde2e7"
darker_background = "#d3d8de"
lighter_background = "#d8dde3"
selection = "#e6bda9"
muted = "#a4acb4"
dark_foreground = "#69737d"
foreground = "#2b2e32"
bright_foreground = "#181b1e"
accent = "#d86105"
red = "#a94f47"
bright_red = "#be5b52"
orange = "#a65c20"
yellow = "#8d7102"
bright_yellow = "#9e8003"
green = "#357a3a"
bright_green = "#3e8b44"
cyan = "#057575"
bright_cyan = "#098585"
blue = "#346aac"
bright_blue = "#3d78c2"
magenta = "#945798"
bright_magenta = "#a763ab"
accent_color = "orange"
