mode = "dark"
background = "#0d2008"
dark_background = "#071704"
darker_background = "#041102"
lighter_background = "#132c0d"
selection = "#333d01"
muted = "#375730"
dark_foreground = "#678c60"
foreground = "#d1e195"
bright_foreground = "#e9f7ba"
accent = "#c0d772"
red = "#f09c7e"
bright_red = "#ffb297"
orange = "#fcb17e"
yellow = "#dbd57e"
bright_yellow = "#f0e988"
green = "#99db9b"
bright_green = "#a8f0a9"
cyan = "#62dedd"
bright_cyan = "#69f4f3"
blue = "#6ebdf3"
bright_blue = "#8ed0ff"
magenta = "#db9fde"
bright_magenta = "#f2aff6"
accent_color = "green"
icon_style = "tinted"
icon_tint = "accent"
