mode = "light"
background = "#ccd99d"
dark_background = "#c2d08c"
darker_background = "#b8c77c"
lighter_background = "#bccc80"
selection = "#88bf7c"
muted = "#8c9b4d"
dark_foreground = "#596b36"
foreground = "#193612"
bright_foreground = "#052200"
accent = "#26541c"
red = "#843825"
bright_red = "#98432e"
orange = "#824103"
yellow = "#655904"
bright_yellow = "#756700"
green = "#275b1b"
bright_green = "#316a23"
cyan = "#025653"
bright_cyan = "#056662"
blue = "#0e4f86"
bright_blue = "#175d9b"
magenta = "#763c72"
bright_magenta = "#884783"
accent_color = "auto"
