mode = "light"
background = "#f4e8d0"
dark_background = "#ecdec1"
darker_background = "#e4d4b4"
lighter_background = "#e9d9b9"
selection = "#edb6ae"
muted = "#b8a786"
dark_foreground = "#7f7050"
foreground = "#372b21"
bright_foreground = "#23180f"
accent = "#b6322b"
red = "#a34942"
bright_red = "#b8554c"
orange = "#9f5618"
yellow = "#866c02"
bright_yellow = "#977a03"
green = "#2f7434"
bright_green = "#38853e"
cyan = "#076f6f"
bright_cyan = "#017f7f"
blue = "#2e64a6"
bright_blue = "#3772bb"
magenta = "#8e5192"
bright_magenta = "#a05da4"
accent_color = "auto"
