mode = "dark"
background = "#2b130f"
dark_background = "#200c09"
darker_background = "#190806"
lighter_background = "#3a1b16"
selection = "#512e0a"
muted = "#6a4039"
dark_foreground = "#a3726a"
foreground = "#e5d5c3"
bright_foreground = "#f9ecde"
accent = "#f2a866"
red = "#e88f85"
bright_red = "#ffa196"
orange = "#f1a774"
yellow = "#e1c570"
bright_yellow = "#f7d979"
green = "#90d192"
bright_green = "#9ee6a0"
cyan = "#57d4d4"
bright_cyan = "#5de9e9"
blue = "#7aaeef"
bright_blue = "#91c1ff"
magenta = "#d195d4"
bright_magenta = "#e8a6ec"
accent_color = "orange"
icon_style = "dark"
