mode = "light"
background = "#f6e5cf"
dark_background = "#efdbc0"
darker_background = "#e6d1b3"
lighter_background = "#ebd5b8"
selection = "#eab7a5"
muted = "#bba485"
dark_foreground = "#836e51"
foreground = "#3a2a20"
bright_foreground = "#26160e"
accent = "#bd5833"
red = "#a34942"
bright_red = "#b8554c"
orange = "#9f5618"
yellow = "#866c02"
bright_yellow = "#977a03"
green = "#2f7434"
bright_green = "#38853e"
cyan = "#076f6f"
bright_cyan = "#017f7f"
blue = "#2e64a6"
bright_blue = "#3772bb"
magenta = "#8e5192"
bright_magenta = "#a05da4"
accent_color = "orange"
