mode = "dark"
background = "#091521"
dark_background = "#040d17"
darker_background = "#020810"
lighter_background = "#0f1f30"
selection = "#013934"
muted = "#31475d"
dark_foreground = "#69839e"
foreground = "#c9dae7"
bright_foreground = "#e3f1fb"
accent = "#0dd7c6"
red = "#fb8276"
bright_red = "#ffa196"
orange = "#ffa15c"
yellow = "#eac33f"
bright_yellow = "#ffd753"
green = "#7bd77f"
bright_green = "#89ec8d"
cyan = "#06d8d9"
bright_cyan = "#0aeeee"
blue = "#6dadff"
bright_blue = "#91c1ff"
magenta = "#dd8be2"
bright_magenta = "#f49bf9"
accent_color = "auto"
icon_style = "dark"
