mode = "dark"
background = "#211f1d"
dark_background = "#181715"
darker_background = "#131110"
lighter_background = "#2d2925"
selection = "#573320"
muted = "#58514a"
dark_foreground = "#887f75"
foreground = "#dad7d3"
bright_foreground = "#f1eeeb"
accent = "#ec7b38"
red = "#d99890"
bright_red = "#f2a89e"
orange = "#e3ad89"
yellow = "#dac68b"
bright_yellow = "#f0da95"
green = "#9ecc9e"
bright_green = "#ace1ad"
cyan = "#7dcece"
bright_cyan = "#85e4e3"
blue = "#89aedd"
bright_blue = "#97c1f7"
magenta = "#c89dca"
bright_magenta = "#dfade1"
accent_color = "orange"
icon_style = "dark"
