mode = "light"
background = "#eae7e5"
dark_background = "#e1ddd9"
darker_background = "#d8d3ce"
lighter_background = "#ddd8d3"
selection = "#e3baa6"
muted = "#ada69f"
dark_foreground = "#797066"
foreground = "#302d2b"
bright_foreground = "#1c1a18"
accent = "#c95b0a"
red = "#9a5049"
bright_red = "#af5c53"
orange = "#985b2d"
yellow = "#846c1b"
bright_yellow = "#957b1e"
green = "#3b723e"
bright_green = "#448247"
cyan = "#076f6f"
bright_cyan = "#017f7f"
blue = "#39659b"
bright_blue = "#4273b0"
magenta = "#89568c"
bright_magenta = "#9b629e"
accent_color = "orange"
