mode = "dark"
background = "#090f18"
dark_background = "#04080f"
darker_background = "#020409"
lighter_background = "#111926"
selection = "#332a01"
muted = "#344052"
dark_foreground = "#728198"
foreground = "#c9dbe0"
bright_foreground = "#e3f1f6"
accent = "#d2be66"
red = "#db9887"
orange = "#e3ae82"
yellow = "#dac870"
green = "#a1cc98"
cyan = "#7bd0c3"
blue = "#89addd"
magenta = "#d199c2"
bright_red = "#f4a895"
bright_yellow = "#f0dc7a"
bright_green = "#b0e1a5"
bright_cyan = "#85e6d7"
bright_blue = "#97c1f7"
bright_magenta = "#e9aad7"
accent_color = "auto"
icon_style = "dark"
