mode = "dark"
background = "#090707"
dark_background = "#040303"
darker_background = "#020101"
lighter_background = "#150f0f"
selection = "#3a1411"
muted = "#3d3332"
dark_foreground = "#8b7c7c"
foreground = "#dbd6d6"
bright_foreground = "#f2eded"
accent = "#ed413b"
red = "#db9289"
bright_red = "#f4a298"
orange = "#e5a880"
yellow = "#d9c37f"
bright_yellow = "#efd689"
green = "#96ca97"
bright_green = "#a5e0a5"
cyan = "#6ecdcc"
bright_cyan = "#76e2e2"
blue = "#81abe0"
bright_blue = "#8fbefa"
magenta = "#c897ca"
bright_magenta = "#dfa8e1"
accent_color = "red"
icon_style = "dark"
