mode = "light"
background = "#f8edd8"
dark_background = "#f0e3ca"
darker_background = "#e7d9bd"
lighter_background = "#ecdec2"
selection = "#ecc0a9"
muted = "#bbac8f"
dark_foreground = "#7e7053"
foreground = "#3a2a20"
bright_foreground = "#26160e"
accent = "#c95b0a"
red = "#a7463e"
bright_red = "#bc5148"
orange = "#a35303"
yellow = "#866c02"
bright_yellow = "#977a03"
green = "#27762f"
bright_green = "#308639"
cyan = "#076f6f"
bright_cyan = "#017f7f"
blue = "#2863ab"
bright_blue = "#3072c1"
magenta = "#904e95"
bright_magenta = "#a35aa7"
accent_color = "orange"
