mode = "dark"
background = "#081209"
dark_background = "#040b05"
lighter_background = "#101d11"
selection = "#19381e"
muted = "#305135"
dark_foreground = "#53895c"
foreground = "#80ee8b"
bright_foreground = "#bfffbd"
accent = "#67ec5b"
red = "#eb8373"
orange = "#e99e5e"
yellow = "#e0cc55"
green = "#6ce36e"
cyan = "#5cd5c7"
blue = "#6bb6d9"
magenta = "#cf94c9"
bright_red = "#ff9786"
bright_yellow = "#f5e05d"
bright_green = "#88fe7d"
bright_cyan = "#64ebdb"
bright_blue = "#75caf2"
bright_magenta = "#e6a4e0"
accent_color = "green"
icon_style = "tinted"
icon_tint = "accent"
