mode = "dark"
background = "#131423"
dark_background = "#0c0d1a"
darker_background = "#070813"
lighter_background = "#1d1e32"
selection = "#023a42"
muted = "#424561"
dark_foreground = "#7a7d9f"
foreground = "#d1d7e9"
bright_foreground = "#e9eefc"
accent = "#43cfe5"
red = "#f2988e"
bright_red = "#ffb0a6"
orange = "#fcb17e"
yellow = "#ebcf7a"
bright_yellow = "#ffe38d"
green = "#99db9b"
bright_green = "#a8f0a9"
cyan = "#62dedd"
bright_cyan = "#69f4f3"
blue = "#84b7f9"
bright_blue = "#a2caff"
magenta = "#db9fde"
bright_magenta = "#f2aff6"
accent_color = "auto"
icon_style = "dark"
