mode = "dark"
background = "#120f0e"
dark_background = "#0a0807"
darker_background = "#050404"
lighter_background = "#1e1817"
selection = "#432010"
muted = "#473d3b"
dark_foreground = "#8b7c7a"
foreground = "#ddd6d1"
bright_foreground = "#f3ede9"
accent = "#fe7222"
red = "#e58c82"
bright_red = "#fe9c91"
orange = "#eea471"
yellow = "#dec26d"
bright_yellow = "#f4d576"
green = "#8dcd8e"
bright_green = "#9be39d"
cyan = "#53d1d0"
bright_cyan = "#59e6e6"
blue = "#77abec"
bright_blue = "#8bbeff"
magenta = "#ce92d1"
bright_magenta = "#e5a3e8"
accent_color = "orange"
icon_style = "tinted"
icon_tint = "accent"
