mode = "dark"
background = "#040609"
dark_background = "#010204"
darker_background = "#000101"
lighter_background = "#090f15"
selection = "#012528"
muted = "#2b343d"
dark_foreground = "#75828f"
foreground = "#cbdae2"
bright_foreground = "#e4f1f7"
accent = "#4ae9f9"
red = "#ed9b92"
bright_red = "#ffb0a6"
orange = "#f7b385"
yellow = "#e8cf83"
bright_yellow = "#ffe38d"
green = "#9ed99f"
bright_green = "#adeeae"
cyan = "#6fdcdb"
bright_cyan = "#77f2f1"
blue = "#89b7f3"
bright_blue = "#a2caff"
magenta = "#d8a1db"
bright_magenta = "#efb2f2"
accent_color = "auto"
icon_style = "dark"
