mode = "dark"
background = "#111810"
dark_background = "#0a1009"
darker_background = "#060b05"
lighter_background = "#1a2417"
selection = "#283916"
muted = "#3e4c3b"
dark_foreground = "#758671"
foreground = "#d8dac3"
bright_foreground = "#eff0de"
accent = "#99c965"
red = "#e58c82"
bright_red = "#fe9c91"
orange = "#eea471"
yellow = "#dec26d"
bright_yellow = "#f4d576"
green = "#8dcd8e"
bright_green = "#9be39d"
cyan = "#53d1d0"
bright_cyan = "#59e6e6"
blue = "#77abec"
bright_blue = "#8bbeff"
magenta = "#ce92d1"
bright_magenta = "#e5a3e8"
accent_color = "green"
icon_style = "dark"
