mode = "dark"
background = "#090909"
dark_background = "#040404"
darker_background = "#020202"
lighter_background = "#141213"
selection = "#002a2b"
muted = "#3c3638"
dark_foreground = "#877d80"
foreground = "#d7d7d7"
bright_foreground = "#eeeeee"
accent = "#22fcfd"
red = "#fd3b2e"
bright_red = "#ff968a"
orange = "#ff9646"
yellow = "#f8f929"
bright_yellow = "#fecf00"
green = "#4df83f"
bright_green = "#5fed6c"
cyan = "#22fcfd"
bright_cyan = "#10e7e7"
blue = "#528dff"
bright_blue = "#86bafe"
magenta = "#f33ff3"
bright_magenta = "#f889ff"
accent_color = "auto"
icon_style = "dark"
