mode = "dark"
background = "#001829"
dark_background = "#00101d"
darker_background = "#000a15"
lighter_background = "#012338"
selection = "#023b39"
muted = "#0b4d71"
dark_foreground = "#4a87b1"
foreground = "#c2dde4"
bright_foreground = "#ddf3f9"
accent = "#3fe2da"
red = "#f08f84"
bright_red = "#fea69c"
orange = "#f9a870"
yellow = "#e7c869"
bright_yellow = "#fddb72"
green = "#8ed690"
bright_green = "#9ceb9f"
cyan = "#49d9d9"
bright_cyan = "#4fefef"
blue = "#79b1f9"
bright_blue = "#97c4fe"
magenta = "#d896db"
bright_magenta = "#efa6f2"
accent_color = "auto"
icon_style = "dark"
