mode = "dark"
background = "#15161a"
dark_background = "#0d0e12"
darker_background = "#08090c"
lighter_background = "#1e2027"
selection = "#4d2621"
muted = "#444752"
dark_foreground = "#7b808e"
foreground = "#dbd8c9"
bright_foreground = "#f2efe3"
accent = "#f45246"
red = "#fb8276"
bright_red = "#ffa196"
orange = "#ffa15c"
yellow = "#f7cd3a"
bright_yellow = "#ffd753"
green = "#7bd77f"
bright_green = "#89ec8d"
cyan = "#06d8d9"
bright_cyan = "#0aeeee"
blue = "#6496f4"
bright_blue = "#91c1ff"
magenta = "#dd8be2"
bright_magenta = "#f49bf9"
accent_color = "auto"
icon_style = "dark"
