mode = "light"
background = "#f6f2e2"
dark_background = "#ede8d4"
darker_background = "#e4dec8"
lighter_background = "#e9e3cd"
selection = "#f0c1ba"
muted = "#b8b199"
dark_foreground = "#787259"
foreground = "#2e2e2b"
bright_foreground = "#1b1b18"
accent = "#d02d27"
red = "#ba3e38"
bright_red = "#cf4a42"
orange = "#ac5701"
yellow = "#a68003"
bright_yellow = "#9e8003"
green = "#097f23"
bright_green = "#18902c"
cyan = "#057575"
bright_cyan = "#098585"
blue = "#2454b3"
bright_blue = "#1e76d8"
magenta = "#9e4aa4"
bright_magenta = "#b156b7"
accent_color = "auto"
