mode = "light"
background = "#f6eedc"
dark_background = "#eee4ce"
darker_background = "#e5dac2"
lighter_background = "#eadec7"
selection = "#a1d6d9"
muted = "#b9ad93"
dark_foreground = "#7c7057"
foreground = "#372b21"
bright_foreground = "#23180f"
accent = "#057176"
red = "#9a5049"
bright_red = "#af5c53"
orange = "#985b2d"
yellow = "#846c1b"
bright_yellow = "#957b1e"
green = "#3b723e"
bright_green = "#448247"
cyan = "#076f6f"
bright_cyan = "#017f7f"
blue = "#39659b"
bright_blue = "#4273b0"
magenta = "#89568c"
bright_magenta = "#9b629e"
accent_color = "auto"
