mode = "dark"
background = "#05070d"
dark_background = "#020306"
darker_background = "#010103"
lighter_background = "#0d101a"
selection = "#2d1f01"
muted = "#303544"
dark_foreground = "#798094"
foreground = "#d0d8e5"
bright_foreground = "#e8effa"
accent = "#eec066"
red = "#f2897e"
bright_red = "#ffa196"
orange = "#faa365"
yellow = "#e6c45a"
bright_yellow = "#fcd863"
green = "#86d489"
bright_green = "#94e997"
cyan = "#2ad7d7"
bright_cyan = "#2eeded"
blue = "#70adfb"
bright_blue = "#91c1ff"
magenta = "#d790db"
bright_magenta = "#eea0f3"
accent_color = "auto"
icon_style = "dark"
